version: '3.8'

services:
  web:
    build: .
    container_name: dss_web_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: uvicorn backend_app:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    container_name: dss_worker
    command: celery -A tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: dss_redis
    ports:
      - "6379:6379"

volumes:
  .:
